
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: C:/SysGCC/raspberry/bin/arm-linux-gnueabihf-g++.exe 
      Build flags: -DQT_QML_DEBUG
      Id flags:  
      
      The output was:
      1
      c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/ld.exe: cannot find /lib/ld-linux-armhf.so.3 inside c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\bin\\../sysroot
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/SysGCC/raspberry/bin/arm-linux-gnueabihf-g++.exe 
      Build flags: -DQT_QML_DEBUG
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        D:/source/Labs/P20/build-PiBoard-sysGCC-Debug/CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/source/Labs/P20/build-PiBoard-sysGCC-Debug/CMakeFiles/CMakeScratch/TryCompile-8fk2n8"
      binary: "D:/source/Labs/P20/build-PiBoard-sysGCC-Debug/CMakeFiles/CMakeScratch/TryCompile-8fk2n8"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "-DQT_QML_DEBUG"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/source/Labs/P20/build-PiBoard-sysGCC-Debug/CMakeFiles/CMakeScratch/TryCompile-8fk2n8'
        
        Run Build Command(s): Z:/School/Qt/Tools/Ninja/ninja.exe -v cmTC_25cbf
        [1/2] C:\\SysGCC\\raspberry\\bin\\arm-linux-gnueabihf-g++.exe   -DQT_QML_DEBUG  -fdiagnostics-color=always   -v -o CMakeFiles/cmTC_25cbf.dir/CMakeCXXCompilerABI.cpp.obj -c Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeCXXCompilerABI.cpp
        Using built-in specs.
        COLLECT_GCC=C:\\SysGCC\\raspberry\\bin\\arm-linux-gnueabihf-g++.exe
        Target: arm-linux-gnueabihf
        Configured with: ../gcc-12-12.2.0/src/configure --with-pkgversion='Raspbian 12.2.0-14+rpi1' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,c++ --with-gcc-major-version-only --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --without-included-gettext --enable-threads=posix --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6+fp --with-float=hard --disable-werror --enable-checking=release --with-sysroot=/mnt/f/gnu/raspberry-bookworm/out/arm-linux-gnueabihf/sysroot --build=x86_64-linux-gnu --disable-nls --host=x86_64-w64-mingw32 --prefix /mnt/f/gnu/raspberry-bookworm/out/ --target=arm-linux-gnueabihf
        Thread model: posix
        Supported LTO compression algorithms: zlib
        gcc version 12.2.0 (Raspbian 12.2.0-14+rpi1) 
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-D' 'QT_QML_DEBUG' '-v' '-o' 'CMakeFiles/cmTC_25cbf.dir/CMakeCXXCompilerABI.cpp.obj' '-c' '-shared-libgcc'  '-mfloat-abi=hard' '-mtls-dialect=gnu' '-marm' '-mlibarch=armv6+fp' '-march=armv6+fp' '-dumpdir' 'CMakeFiles/cmTC_25cbf.dir/'
         c:/sysgcc/raspberry/bin/../libexec/gcc/arm-linux-gnueabihf/12/cc1plus.exe -quiet -v -imultilib . -imultiarch arm-linux-gnueabihf -iprefix c:\\sysgcc\\raspberry\\bin\\../lib/gcc/arm-linux-gnueabihf/12/ -isysroot c:\\sysgcc\\raspberry\\bin\\../arm-linux-gnueabihf/sysroot -D_GNU_SOURCE -D QT_QML_DEBUG Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeCXXCompilerABI.cpp -quiet -dumpdir CMakeFiles/cmTC_25cbf.dir/ -dumpbase CMakeCXXCompilerABI.cpp.cpp -dumpbase-ext .cpp -mfloat-abi=hard -mtls-dialect=gnu -marm -mlibarch=armv6+fp -march=armv6+fp -version -fdiagnostics-color=always -o C:\\Users\\glenm\\AppData\\Local\\Temp\\ccYSLIAI.s
        GNU C++17 (Raspbian 12.2.0-14+rpi1) version 12.2.0 (arm-linux-gnueabihf)
        	compiled by GNU C version 10-win32 20220113, GMP version 4.3.2, MPFR version 3.1.6, MPC version 1.0.3, isl version none
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        ignoring nonexistent directory "c:\\sysgcc\\raspberry\\include\\arm-linux-gnueabihf\\c++\\12"
        ignoring nonexistent directory "c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\include\\arm-linux-gnueabihf\\c++\\12\\arm-linux-gnueabihf"
        ignoring duplicate directory "c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\include\\c++\\12"
        ignoring nonexistent directory "c:\\sysgcc\\raspberry\\include\\arm-linux-gnueabihf\\c++\\12"
        ignoring duplicate directory "c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\include\\c++\\12\\backward"
        ignoring duplicate directory "c:\\sysgcc\\raspberry\\lib\\gcc\\arm-linux-gnueabihf\\12\\include"
        ignoring nonexistent directory "c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\sysroot\\mnt\\f\\gnu\\raspberry-bookworm\\out\\include\\arm-linux-gnueabihf"
        ignoring nonexistent directory "c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\sysroot\\mnt\\f\\gnu\\raspberry-bookworm\\out\\include"
        ignoring duplicate directory "c:\\sysgcc\\raspberry\\lib\\gcc\\arm-linux-gnueabihf\\12\\include-fixed"
        ignoring duplicate directory "c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\include"
        #include "..." search starts here:
        #include <...> search starts here:
         c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\include\\c++\\12
         c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\include\\c++\\12\\backward
         c:\\sysgcc\\raspberry\\lib\\gcc\\arm-linux-gnueabihf\\12\\include
         c:\\sysgcc\\raspberry\\lib\\gcc\\arm-linux-gnueabihf\\12\\include-fixed
         c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\include
         c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\include\\arm-linux-gnueabihf\\c++\\12
         c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\sysroot\\usr\\include\\arm-linux-gnueabihf
         c:\\sysgcc\\raspberry\\arm-linux-gnueabihf\\sysroot\\usr\\include
        End of search list.
        GNU C++17 (Raspbian 12.2.0-14+rpi1) version 12.2.0 (arm-linux-gnueabihf)
        	compiled by GNU C version 10-win32 20220113, GMP version 4.3.2, MPFR version 3.1.6, MPC version 1.0.3, isl version none
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        Compiler executable checksum: 1cb6a7fd1911c5a463789966aafd624d
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-D' 'QT_QML_DEBUG' '-v' '-o' 'CMakeFiles/cmTC_25cbf.dir/CMakeCXXCompilerABI.cpp.obj' '-c' '-shared-libgcc'  '-mfloat-abi=hard' '-mtls-dialect=gnu' '-marm' '-mlibarch=armv6+fp' '-march=armv6+fp' '-dumpdir' 'CMakeFiles/cmTC_25cbf.dir/'
         c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/as.exe -v -march=armv6 -mfloat-abi=hard -meabi=5 -o CMakeFiles/cmTC_25cbf.dir/CMakeCXXCompilerABI.cpp.obj C:\\Users\\glenm\\AppData\\Local\\Temp\\ccYSLIAI.s
        GNU assembler version 2.40 (arm-linux-gnueabihf) using BFD version (GNU Binutils for Raspbian) 2.40
        COMPILER_PATH=c:/sysgcc/raspberry/bin/../libexec/gcc/arm-linux-gnueabihf/12/;c:/sysgcc/raspberry/bin/../libexec/gcc/arm-linux-gnueabihf/;c:/sysgcc/raspberry/bin/../libexec/gcc/;c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/
        LIBRARY_PATH=c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/;c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/;c:/sysgcc/raspberry/bin/../lib/gcc/;c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/lib/;c:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/lib/arm-linux-gnueabihf/;c:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/lib/;c:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/usr/lib/arm-linux-gnueabihf/;c:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/usr/lib/
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-D' 'QT_QML_DEBUG' '-v' '-o' 'CMakeFiles/cmTC_25cbf.dir/CMakeCXXCompilerABI.cpp.obj' '-c' '-shared-libgcc'  '-mfloat-abi=hard' '-mtls-dialect=gnu' '-marm' '-mlibarch=armv6+fp' '-march=armv6+fp' '-dumpdir' 'CMakeFiles/cmTC_25cbf.dir/CMakeCXXCompilerABI.cpp.'
        [2/2] cmd.exe /C "cd . && C:\\SysGCC\\raspberry\\bin\\arm-linux-gnueabihf-g++.exe -DQT_QML_DEBUG -v CMakeFiles/cmTC_25cbf.dir/CMakeCXXCompilerABI.cpp.obj -o cmTC_25cbf.exe -Wl,--out-implib,libcmTC_25cbf.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd ."
        \x1b[31mFAILED: \x1b[0mcmTC_25cbf.exe 
        cmd.exe /C "cd . && C:\\SysGCC\\raspberry\\bin\\arm-linux-gnueabihf-g++.exe -DQT_QML_DEBUG -v CMakeFiles/cmTC_25cbf.dir/CMakeCXXCompilerABI.cpp.obj -o cmTC_25cbf.exe -Wl,--out-implib,libcmTC_25cbf.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd ."
        Using built-in specs.
        COLLECT_GCC=C:\\SysGCC\\raspberry\\bin\\arm-linux-gnueabihf-g++.exe
        COLLECT_LTO_WRAPPER=c:/sysgcc/raspberry/bin/../libexec/gcc/arm-linux-gnueabihf/12/lto-wrapper.exe
        Target: arm-linux-gnueabihf
        Configured with: ../gcc-12-12.2.0/src/configure --with-pkgversion='Raspbian 12.2.0-14+rpi1' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,c++ --with-gcc-major-version-only --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --without-included-gettext --enable-threads=posix --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6+fp --with-float=hard --disable-werror --enable-checking=release --with-sysroot=/mnt/f/gnu/raspberry-bookworm/out/arm-linux-gnueabihf/sysroot --build=x86_64-linux-gnu --disable-nls --host=x86_64-w64-mingw32 --prefix /mnt/f/gnu/raspberry-bookworm/out/ --target=arm-linux-gnueabihf
        Thread model: posix
        Supported LTO compression algorithms: zlib
        gcc version 12.2.0 (Raspbian 12.2.0-14+rpi1) 
        COMPILER_PATH=c:/sysgcc/raspberry/bin/../libexec/gcc/arm-linux-gnueabihf/12/;c:/sysgcc/raspberry/bin/../libexec/gcc/arm-linux-gnueabihf/;c:/sysgcc/raspberry/bin/../libexec/gcc/;c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/
        LIBRARY_PATH=c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/;c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/;c:/sysgcc/raspberry/bin/../lib/gcc/;c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/lib/;c:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/lib/arm-linux-gnueabihf/;c:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/lib/;c:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/usr/lib/arm-linux-gnueabihf/;c:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/usr/lib/
        COLLECT_GCC_OPTIONS='-D' 'QT_QML_DEBUG' '-v' '-o' 'cmTC_25cbf.exe' '-shared-libgcc'  '-mfloat-abi=hard' '-mtls-dialect=gnu' '-marm' '-mlibarch=armv6+fp' '-march=armv6+fp' '-dumpdir' 'cmTC_25cbf.'
         c:/sysgcc/raspberry/bin/../libexec/gcc/arm-linux-gnueabihf/12/collect2.exe -dynamic-linker /lib/ld-linux-armhf.so.3 -X --hash-style=gnu --as-needed -m armelf_linux_eabi -o cmTC_25cbf.exe c:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/lib/arm-linux-gnueabihf/crt1.o c:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/lib/arm-linux-gnueabihf/crti.o c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/lib/crtbegin.o -Lc:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12 -Lc:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf -Lc:/sysgcc/raspberry/bin/../lib/gcc -Lc:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/lib -Lc:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/lib/arm-linux-gnueabihf -Lc:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/lib -Lc:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/usr/lib/arm-linux-gnueabihf -Lc:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/usr/lib CMakeFiles/cmTC_25cbf.dir/CMakeCXXCompilerABI.cpp.obj --out-implib libcmTC_25cbf.dll.a --major-image-version 0 --minor-image-version 0 -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/lib/crtend.o c:/sysgcc/raspberry/bin/../arm-linux-gnueabihf/sysroot/lib/arm-linux-gnueabihf/crtn.o
        c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/ld.exe: unrecognized option '--major-image-version'
        c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/ld.exe: use the --help option for usage information
        collect2.exe: error: ld returned 1 exit status
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "Z:/School/Qt/Tools/CMake_64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:49 (try_compile)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Check for working CXX compiler: C:/SysGCC/raspberry/bin/arm-linux-gnueabihf-g++.exe"
    directories:
      source: "D:/source/Labs/P20/build-PiBoard-sysGCC-Debug/CMakeFiles/CMakeScratch/TryCompile-s54a25"
      binary: "D:/source/Labs/P20/build-PiBoard-sysGCC-Debug/CMakeFiles/CMakeScratch/TryCompile-s54a25"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "-DQT_QML_DEBUG"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'D:/source/Labs/P20/build-PiBoard-sysGCC-Debug/CMakeFiles/CMakeScratch/TryCompile-s54a25'
        
        Run Build Command(s): Z:/School/Qt/Tools/Ninja/ninja.exe -v cmTC_26225
        [1/2] C:\\SysGCC\\raspberry\\bin\\arm-linux-gnueabihf-g++.exe   -DQT_QML_DEBUG  -fdiagnostics-color=always -o CMakeFiles/cmTC_26225.dir/testCXXCompiler.cxx.obj -c D:/source/Labs/P20/build-PiBoard-sysGCC-Debug/CMakeFiles/CMakeScratch/TryCompile-s54a25/testCXXCompiler.cxx
        [2/2] cmd.exe /C "cd . && C:\\SysGCC\\raspberry\\bin\\arm-linux-gnueabihf-g++.exe -DQT_QML_DEBUG  CMakeFiles/cmTC_26225.dir/testCXXCompiler.cxx.obj -o cmTC_26225.exe -Wl,--out-implib,libcmTC_26225.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
        \x1b[31mFAILED: \x1b[0mcmTC_26225.exe 
        cmd.exe /C "cd . && C:\\SysGCC\\raspberry\\bin\\arm-linux-gnueabihf-g++.exe -DQT_QML_DEBUG  CMakeFiles/cmTC_26225.dir/testCXXCompiler.cxx.obj -o cmTC_26225.exe -Wl,--out-implib,libcmTC_26225.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
        c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/ld.exe: unrecognized option '--major-image-version'
        c:/sysgcc/raspberry/bin/../lib/gcc/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/ld.exe: use the --help option for usage information
        collect2.exe: error: ld returned 1 exit status
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
